spring.application.name=wealthwise

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/wealthwise
spring.datasource.username=postgres
spring.datasource.password=rithwik1234

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# Caching Configuration
spring.cache.type=simple
spring.cache.redis.time-to-live=15m
spring.cache.redis.cache-null-values=false

# Market API Configurations
application.market.finnhub.url=https://finnhub.io/api/v1
application.market.finnhub.token=d9bl85pr01qpn20ust10d9bl85pr01qpn20ust1g